name: "deploy"

on:
    push:
        branches:
            - main
        paths:
            - "III/app/**"
            - "III/app/Dockerfile"
            - ".github/workflows/III-deploy.yaml"

jobs:
    build-push:
        outputs:
            image_tag: ${{ steps.tag.outputs.image_tag }}

        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: setup docker buildx
              uses: docker/setup-buildx-action@v3

            - name: log in to docker hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: set image tag
              id: tag
              run: echo "image_tag=${{ secrets.DOCKERHUB_USER }}/iii-app:${{ github.sha }}" >> $GITHUB_OUTPUT

            - name: build and push image
              uses: docker/build-push-action@v6
              with:
                  context: ./III/app
                  file: ./III/app/Dockerfile
                  push: true
                  tags: ${{ steps.tag.outputs.image_tag }}

    deploy:
        runs-on: ubuntu-latest
        needs: [build-push]
        steps:
            - uses: actions/checkout@v5
            - name: apply terraform
              run: |
                  set -e
