name: "deploy"

on:
    push:
        branches:
            - main
        paths:
            - "III/app/**"
            - "III/app/Dockerfile"
            - ".github/workflows/III-deploy.yaml"

jobs:
    build-push:
        outputs:
            image_tag: ${{ github.sha }}

        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: setup docker buildx
              uses: docker/setup-buildx-action@v3

            - name: log in to docker hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USER }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: build and push image
              uses: docker/build-push-action@v6
              with:
                  context: ./III/app
                  file: ./III/app/Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USER }}/iii-app:${{ github.sha }}

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: [build-push]
    #     steps:
    #         - name: setup terraform
    #           uses: hashicorp/setup-terraform@v3
    #           with:
    #               terraform_version: "latest"
    #               cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    #         - uses: actions/checkout@v5
    #         - name: run terraform
    #           run: |
    #               set -e

    #               cd III/tf

    #               terraform init -input=false
    #               terraform apply -input=false -auto-approve
    #           env:
    #               TF_VAR_IMAGE_TAG: ${{ secrets.DOCKERHUB_USER }}/iii-app:${{ needs.build-push.outputs.image_tag }}
